### ISSUE TITLE
Баг Главного меню и Названия

### ISSUE THREAD

**Issue by zavalishin-arseniy** [emaxximov/mm_ez_money_bot#8]
Когда вводишь Имя достижения и нажимаешь на Главное меню, то оно называет достижение "Главное меню".

**Comment by emaxximov** [comment]
Это по большому счету не баг, такое поведение и ожидается, но могу попробовать принудительно убирать кнопки на этапе ввода имени.

**Comment by emaxximov** [comment]
Попробуй сейчас.

**Comment by zavalishin-arseniy** [comment]
Не работает.

**Comment by emaxximov** [comment]
Я забыл пересобрать, давай еще раз))

**Comment by zavalishin-arseniy** [comment]
Ты убил его!

**Comment by emaxximov** [comment]
А так?

**Comment by zavalishin-arseniy** [comment]
Оно заработало, но не сразу.
